# Page settings
baseurl = "/"
title = "NURIGO"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "NURIGO"
    home = "HOME"
    testimonials = "Testimonials"
    services = "NURIGO LIFE"
    about = "ABOUT US"
    work = "IP"
    contact = "CONTACT US"
    roadmap = "ROADMAP"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "메시지 플랫폼 서비스"
    subtitle = '세상에서 가장 쉽게 메시지를 발송할 수 있도록 도와드립니다'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "쉬운 발송"
    description = "쿨에스엠에스 플랫폼을 기반으로 하는 응용프로그램 및 서비스 중에서 나에게 맞는 솔루션을 찾아보세요."
    url = "https://www.coolsms.co.kr/apps"
    button = "Find Apps"
    icon = "icon-rocket"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "쉬운 개발"
    description = "쿨에스엠에스는 REST API와 오픈된 SDK를 이용하여 폭 넓은 언어와 플랫폼 환경을 쉽고 빠르게 지원합니다."
    url = "https://www.coolsms.co.kr/developer"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "수익 공유"
    description = "앱에 등록된 앱 아이디를 통하여 최소 건당 2원씩 수익이 공유되며 누적된 수익은 언제든 정산 요청을 할 수 있습니다."
    url = "https://www.coolsms.co.kr/app_intro"
    button = "Check It"
    icon = "icon-dollar"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
#    url = "https://vimeo.com/80611529" # old
    url = "https://vimeo.com/232157734" # new


  # Work section
  [params.work]
    enable = true
    title = "Intellectual Property"
    description = "그동안 누리고가 노력해 온 것을 보여주는 공식 인증서들입니다"
    footertext = ''

    [[params.work.row]]
      img = "trademark-coolsms.jpg"
      alt = "서비스등록표"
      title = "서비스등록표"
      subtitle = ""

    [[params.work.row]]
      img = "patent-push.jpg"
      alt = "특허 10-1597977"
      title = "특허 10-1597977"
      subtitle = ""

    [[params.work.row]]
      img = "patent-ars.jpg"
      alt = "특허 10-1701116"
      title = "특허 10-1701116"
      subtitle = ""

    [[params.work.row]]
      img = "patent-mo.jpg"
      alt = "특허 10-1648031"
      title = "특허 10-1648031"
      subtitle = ""

    [[params.work.row]]
      img = "rnd.jpg"
      alt = "연구전담부서인증서"
      title = "연구전담부서인증서"
      subtitle = ""

    [[params.work.row]]
      img = "venture.jpg"
      alt = "벤처기업확인서"
      title = "벤처기업확인서"
      subtitle = ""

 # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "NURIGO LIFE"
    description = "개발자가 행복한 기업"

    [[params.services.item]]
      title = "수평적 리더쉽"
      description = "회사 내에서 영어닉으로 호칭. 자율성을 갖고 업무를 스스로 계획하고 실천하는 상향식 업무프로세스. 10배의 성과자에게 10배의 연봉 지급을 원칙으로하는 공정한 분배시스템"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "능동적 & 능률적 업무문화"
      description = "탄력근무제 주 40 시간 근무제로 아침8시 ~ 10시 사이 출근시간을 선택. 매일 스탠딩 회의로 방향을 점검하는 칸반 기반의 업무프로세스. TDD 준수, Github 의 Pull Request 기반의 코드 리뷰.  Travis-CI, Jenkins, Spinnaker 를 사용하여 CI/CD 의 자동화."
      icon = "icon-layers2"

    [[params.services.item]]
      title = "복지"
      description = "연 15일 휴가제 및 3년 마다 15일 안식휴가<br>도서구매 지원 - 매월 한 권의 도서구입비 지원<br>무한 간식 제공 - 끝없이 채워지는 간식<br>레포츠 데이 - 두 달에 한번 금요일에 떠나는 에너지 충전 여행" 
      icon = "icon-shield"

      [[params.services.item]]
      title = "채용"
      description = "NodeJS 개발 및 서비스 운영 전문가 항시 채용중. 인재 추천 후 채용시 200만원 지급."      
      icon = "icon-user"

  # Loadmap section
  [params.roadmap]
    enable = true
    title = "ROADMAP"
    description = "효율적인 개발 환경을 위해<br>개발자가 일하기 좋은 환경으로 점진적 업그레이드"

    [[params.roadmap.item]]
      title = "업무환경"
      description = "2020 .. 호텔 요리사 채용(호텔식 요리 제공)<br>2022 .. 누리고 어린이집 오픈<br>2024 .. 스톡옵션 제공<br>"

    [[params.roadmap.item]]
      title = "평균연봉"
      description = "2020 .. 4,000만원<br>2021 .. 4,600만원<br>2022 ..  5,200만원<br>2025 .. 6,400만원<br>2030 .. 실리콘밸리 수준의 연봉"

    [[params.roadmap.item]]
      title = "글로벌 계획"
      description = "2020 .. 대만(Taiwan) 서비스 런칭<br>2022 .. 대만을 비롯한 중국어권 서비스 본격화<br>2024 .. 영어권 국가로 확대<br>2026 .. 모든 서비스 및 제품을 글로벌 기준에 맞춤"


  # About section
  [params.about]
    enable = true
    title = "ABOUT US"
    description = "쿨에스엠에스를 세상에서 가장 쉬운 메시지 플랫폼 서비스로<br>만들어 가고 있는 사람들 입니다."

    [[params.about.item]]
      name = "Ashley Yang"
      position = "APAC Service Manager"
      description = "대만 출신으로 중국어를 구사할 수 있고 중국어권 지역의 서비스 론칭 및 운영을 지원하고 있습니다."
      img = "ashley.jpg"
      alt = "Ashley Yang"
#      social = [
#        ["icon-twitter", "#"],
#        ["icon-facebook", "#"],
#        ["icon-dribbble", "#"]
#      ]      


    [[params.about.item]]
      name = "Eden Cha"
      position = "Front-End Senior Developer"
      description = '"Brainy is the new sexy"'
      img = "eden.jpg"
      alt = "Eden Cha"

    [[params.about.item]]
      name = "Hosy Lee"
      position = "Back-End Senior Developer"
      description = '개발자들의 수익을 위해 힘쓰고 있습니다. "부자가 되고 싶다면 주위 사람이 먼저 부자가 되게 도와라" - 마윈 알리바바 회장'
      img = "hosy.jpg"
      alt = "Hosy Lee"

    [[params.about.item]]
      name = "Steven Jang"
      position = "Back-End Developer"
      description = '"노력의 척도는 결과다."'
      img = "Steven.jpg"
      alt = "Steven Jang"

    [[params.about.item]]
      name = "Wiley Choi"
      position = "Founder & CEO"
      description = "현재에 안주하지 않고 반복적인 개선을 통해 고객의 요구를 뛰어넘어 전에 없던 놀라운 메시징 플랫폼 서비스를 만들어 가겠습니다."
      img = "wiley.jpg"
      alt = "Wiley Choi"

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = false
    map = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "서울특별시 금천구 두산로 70 현대지식산업센터 A동 1811호"],
#        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "contact@nurigo.net"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '<br>&copy; NURIGO All Rights Reserved.'
